
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\t\xa4\xc3K\xeb>\xa2\x84\xaf\xabKY\x0e\xc42x'
    
_lr_action_items = {'HEADER':([4,7,8,],[13,-9,-10,]),'NEWLINE':([1,2,4,7,8,10,12,13,16,],[8,9,-8,-9,-10,-7,9,16,-6,]),'WORD':([0,1,2,4,6,7,8,9,10,11,15,],[1,1,1,-8,1,-9,-10,-11,-7,-5,-4,]),'$end':([0,3,5,6,9,11,14,15,],[-3,-1,0,-3,-11,-5,-2,-4,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'header':([4,],[12,]),'paragraph':([0,6,],[2,2,]),'blank':([2,12,],[11,15,]),'block_list':([0,6,],[3,14,]),'line':([0,1,2,6,],[4,7,10,4,]),'document':([0,],[5,]),'block':([0,6,],[6,6,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> document","S'",1,None,None,None),
  ('document -> block_list','document',1,'p_document','newspaper/yacc2.py',12),
  ('block_list -> block block_list','block_list',2,'p_blocklist','newspaper/yacc2.py',18),
  ('block_list -> <empty>','block_list',0,'p_blocklist','newspaper/yacc2.py',19),
  ('block -> line header blank','block',3,'p_block','newspaper/yacc2.py',28),
  ('block -> paragraph blank','block',2,'p_block','newspaper/yacc2.py',29),
  ('header -> HEADER NEWLINE','header',2,'p_header','newspaper/yacc2.py',35),
  ('paragraph -> paragraph line','paragraph',2,'p_paragraph','newspaper/yacc2.py',41),
  ('paragraph -> line','paragraph',1,'p_paragraph','newspaper/yacc2.py',42),
  ('line -> WORD line','line',2,'p_line','newspaper/yacc2.py',51),
  ('line -> WORD NEWLINE','line',2,'p_line','newspaper/yacc2.py',52),
  ('blank -> NEWLINE','blank',1,'p_blank','newspaper/yacc2.py',62),
]
